version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /power-sim
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /infra
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: terraform
    directory: /infra
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /infra/services/fake-telemetry
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /infra/services/modbus-ingestor
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
