apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - service-accounts.yaml
  - power-sim.yaml
  - modbus-ingestor.yaml
  - influxdb.yaml
  - grafana.yaml
  - network-policies.yaml

