apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: gridguard-ot
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: gridguard-ingestion
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: gridguard-observability
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cluster-dns
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingestor-to-power-sim
  namespace: gridguard-ot
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: power-sim
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gridguard-ingestion
          podSelector:
            matchLabels:
              app.kubernetes.io/name: modbus-ingestor
      ports:
        - protocol: TCP
          port: 1502
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingestor-egress
  namespace: gridguard-ingestion
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: modbus-ingestor
  policyTypes: ["Egress"]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gridguard-ot
          podSelector:
            matchLabels:
              app.kubernetes.io/name: power-sim
      ports:
        - protocol: TCP
          port: 1502
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gridguard-observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: influxdb
      ports:
        - protocol: TCP
          port: 8086
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-approved-influxdb-clients
  namespace: gridguard-observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: influxdb
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gridguard-ingestion
          podSelector:
            matchLabels:
              app.kubernetes.io/name: modbus-ingestor
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gridguard-observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
      ports:
        - protocol: TCP
          port: 8086
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-egress
  namespace: gridguard-observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  policyTypes: ["Egress"]
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: influxdb
      ports:
        - protocol: TCP
          port: 8086
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-operator
  namespace: gridguard-observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              gridguard.io/role: operator
      ports:
        - protocol: TCP
          port: 3000
