apiVersion: v1
kind: ServiceAccount
metadata:
  name: power-sim
  namespace: gridguard-ot
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: modbus-ingestor
  namespace: gridguard-ingestion
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb
  namespace: gridguard-observability
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: gridguard-observability
automountServiceAccountToken: false

